spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=studentskiservisrti@gmail.com
spring.mail.password=biguflveogluyghs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=true
spring.ldap.urls=ldap://147.91.11.76:636
spring.ldap.base=dc=ETF,dc=LOCAL
studentski.radovi.dir=studentskiRadovi
demonstratori.dir=demonstratori
